jenkins:
  systemMessage: "\n URL \n"
  numExecutors: 3
jobs:
  - script: >
      pipelineJob('SEED') {
        definition {
          cps {
            sandbox(true)
            script(
              pipeline {
                agent any
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                }
              })
          }
        }
      }
