jenkins:
  systemMessage: "\n URL \n"
  numExecutors: 3
jobs:
  - script: |
    pipelineJob('configuration-as-code') {
          pipeline {
            agent any
            stages {
              stage("TEST") {
                  steps {
                      echo "HELLO, THIS WORKS!!"
                   }
              }
            }
           }     
      }
